import { config } from './config.mjs';
import { shell, escape } from './render.mjs';
import { articles, articlePath, articleDate, readingMinutes } from './articles.mjs';
const url = path => config.origin.replace(/\/$/, '') + path;
const mapUrl = 'https://yandex.ru/maps/org/yuzhnyye_vorota/1170329985/';
const image = name => `/assets/${name}${/\.(webp|png|jpg)$/.test(name)?'':'.jpg'}`;

function blogCard(a){return `<article class="journal-card"><a href="${articlePath(a)}" class="journal-image" tabindex="-1" aria-hidden="true"><img src="${image(a.image)}" alt="" width="640" height="420" loading="lazy"></a><div class="journal-card-copy"><p class="article-meta">${escape(a.category)} · ${readingMinutes(a)} мин чтения</p><h2><a href="${articlePath(a)}">${escape(a.title)}</a></h2><p>${escape(a.description)}</p></div></article>`;}

export function home(){
 const title='MOKWHEEL — магазин электровелосипедов в Москве';
 const description='MOKWHEEL, QRONGE и PUCKIPUPPY в магазине на Южных воротах. Электровелосипеды, оптовые партии для бизнеса, самовывоз и отправка ТК. Телефон и карта проезда.';
 return shell({title,description,path:'/',schema:{'@context':'https://schema.org','@type':'BikeStore',name:'MOKWHEEL',url:url('/'),image:url(image('store-front')),telephone:config.phoneHref,address:{'@type':'PostalAddress',addressLocality:'Москва',streetAddress:config.pickup,addressCountry:'RU'}},body:`
 <section class="container store-hero"><div class="store-intro"><h1>Магазин электровелосипедов<br>в Москве</h1><p class="store-hero-address">${config.pickup}</p><a class="store-hero-phone" href="tel:${config.phoneHref}" data-goal="phone_click">${config.phone}</a><div class="store-actions"><a class="btn dark" href="/opt/">Оптовый каталог</a><a class="text-link" href="#contacts">Как добраться</a></div></div><figure class="store-cover"><img src="${image('store-front')}" alt="Вход в магазин MOKWHEEL на Южных воротах" width="1280" height="960" fetchpriority="high"></figure></section>
 <section class="container store-brands" id="brands" aria-label="Бренды в магазине"><ul class="brand-logos"><li><img src="/assets/brands/mokwheel.png" alt="MOKWHEEL" width="896" height="82" loading="lazy"></li><li><img class="qronge-logo" src="/assets/brands/qronge.png" alt="QRONGE" width="720" height="98" loading="lazy"></li><li><img src="/assets/brands/puckipuppy.png" alt="PUCKIPUPPY" width="7500" height="833" loading="lazy"></li></ul></section>
 <section class="container store-section shop-photos"><div class="store-section-heading"><h2>В магазине</h2></div><div class="shop-photo-grid"><figure><img src="${image('store-courier-bikes')}" alt="Курьерские электровелосипеды QRONGE в магазине" width="960" height="1280" loading="lazy"></figure><figure><img src="${image('store-puckipuppy')}" alt="Велосипеды PUCKIPUPPY на витрине" width="960" height="1280" loading="lazy"></figure><figure><img src="${image('store-parts')}" alt="Комплектующие и аксессуары для электротранспорта" width="960" height="1280" loading="lazy"></figure></div></section>
 <section class="contact-section" id="contacts"><div class="container contact-grid"><div><h2>Адрес и контакты</h2><address>${config.pickup}</address><p>Наличие нужной модели можно уточнить по телефону.</p><a class="contact-phone" href="tel:${config.phoneHref}" data-goal="phone_click">${config.phone}</a><a class="contact-secondary" href="tel:+79258318777">${config.secondPhone}</a><div class="store-actions"><a class="btn dark" href="${mapUrl}" target="_blank" rel="noopener" data-goal="directions_click">Маршрут в Яндекс Картах</a></div><p class="contact-note">Самовывоз или отправка любой ТК за счёт покупателя. Отправка после 100% оплаты.</p></div><div class="map-panel"><iframe title="ТК Южные ворота на Яндекс Картах" src="https://yandex.ru/map-widget/v1/?mode=search&amp;oid=1170329985&amp;ol=biz&amp;z=15" loading="lazy" allowfullscreen referrerpolicy="strict-origin-when-cross-origin"></iframe><p>На карте — торговый комплекс. Внутри: выход 5, линия Ж8, павильоны 122–128. <a href="${mapUrl}" target="_blank" rel="noopener">Открыть карту отдельно</a></p></div></div></section>
 <section class="container store-section"><div class="store-section-heading"><h2>Статьи о закупке и эксплуатации</h2><a class="text-link" href="/blog/">Все статьи →</a></div><div class="journal-grid">${articles.slice(0,3).map(blogCard).join('')}</div></section>`});
}

export function blogPage(){return shell({title:'Блог MOKWHEEL — велосипеды для курьеров, доставки и оптового бизнеса',description:'12 практических материалов о выборе курьерских велосипедов, оптовой закупке, аренде, батареях, обслуживании и доставке партий.',path:'/blog/',schema:{'@context':'https://schema.org','@type':'Blog',name:'Блог MOKWHEEL',url:url('/blog/'),blogPost:articles.map(a=>({'@type':'BlogPosting',headline:a.title,url:url(articlePath(a))}))},body:`<section class="container journal-intro"><h1>Блог</h1><p>Выбор велосипедов, закупка, обслуживание и работа курьерского парка.</p><nav class="journal-topics" aria-label="Темы блога"><a href="#choice">Выбор техники</a><a href="#business">Парк и аренда</a><a href="#purchase">Закупка и доставка</a></nav></section>${[
 ['choice','Выбрать технику',['Выбор техники','Доставка','Модели и бренды']],
 ['business','Организовать работу парка',['Управление парком','Арендный бизнес','Экономика парка']],
 ['purchase','Купить и получить партию',['Оптовая закупка','Логистика']]
 ].map(([id,title,categories])=>`<section class="container journal-section" id="${id}"><h2 class="journal-section-title">${title}</h2><div class="journal-grid">${articles.filter(a=>categories.includes(a.category)).map(blogCard).join('')}</div></section>`).join('')}`});}

export function articlePage(a){
 const related=articles.filter(item=>a.related.includes(item.slug));
 return shell({title:`${a.title} | Блог MOKWHEEL`,description:a.description,path:articlePath(a),image:image(a.image),type:'article',schema:{'@context':'https://schema.org','@type':'BlogPosting',headline:a.title,description:a.description,datePublished:articleDate,dateModified:articleDate,inLanguage:'ru-RU',image:url(image(a.image)),mainEntityOfPage:url(articlePath(a)),author:{'@type':'Organization',name:'MOKWHEEL',url:url('/')},publisher:{'@type':'Organization',name:'MOKWHEEL',url:url('/')}},body:`<article class="reading-layout"><div class="article-heading"><nav class="breadcrumbs" aria-label="Хлебные крошки"><a href="/">Главная</a><span>/</span><a href="/blog/">Блог</a></nav><p class="article-meta">${escape(a.category)} · ${readingMinutes(a)} мин чтения</p><h1>${escape(a.title)}</h1><p class="article-lead">${escape(a.lead)}</p><div class="article-byline"><span class="author-mark" aria-hidden="true">M</span><span>MOKWHEEL · магазин электровелосипедов<br><time datetime="${articleDate}">4 октября 2026</time></span></div></div><figure class="article-cover"><img src="${image(a.image)}" alt="${escape(a.imageAlt)}" width="1280" height="850" fetchpriority="high"><figcaption>Редакционная иллюстрация, созданная с помощью ИИ</figcaption></figure><div class="article-body"><nav class="article-contents" aria-label="Содержание статьи"><h2>В этой статье</h2><ol>${a.sections.map((s,i)=>`<li><a href="#section-${i+1}">${escape(s.title)}</a></li>`).join('')}</ol></nav>${a.sections.map((s,i)=>`<section id="section-${i+1}"><h2>${escape(s.title)}</h2>${s.paragraphs.map(p=>`<p>${escape(p)}</p>`).join('')}${s.list?`<ul>${s.list.map(item=>`<li>${escape(item)}</li>`).join('')}</ul>`:''}</section>`).join('')}<aside class="article-order"><h2>Оптовый каталог</h2><p>Выберите модели в оптовом каталоге или обсудите партию с нами. Подтвердим наличие, комплектацию и условия получения.</p><div class="store-actions"><a class="btn dark" href="/opt/">Смотреть оптовый каталог</a><a href="tel:${config.phoneHref}" data-goal="phone_click">${config.phone}</a></div></aside></div></article><section class="container journal-section"><h2 class="journal-section-title">Читайте дальше</h2><div class="journal-grid related-articles">${related.map(blogCard).join('')}</div></section>`});
}

export const pendingDocuments={
 'sales-agreement':{title:'Договор купли-продажи / поставки',description:'Шаблон договора готовится к публикации. Перед оплатой запросите у менеджера документ с реквизитами продавца, составом заказа, стоимостью и условиями поставки.'},
 'warranty':{title:'Гарантия и порядок обращения',description:'Общий документ готовится к публикации. Условия гарантии, обслуживания и обращения по конкретной комплектации уточняйте у менеджера до покупки.'},
 'company-details':{title:'Реквизиты продавца',description:'Полные реквизиты для оформления покупки уточняйте у менеджера до оплаты.'}
};
export function legalPage(){
 const entries=[['/privacy/','Политика обработки персональных данных','Какие данные получает сайт и как с ними работает.','На сайте'],['/privacy/#consent','Согласие на обработку данных','Условия обработки данных при отправке заявки.','На сайте'],['/terms/','Условия предложения','Оптовое количество, цена, оплата и получение заказа.','На сайте'],...Object.entries(pendingDocuments).map(([slug,d])=>[`/legal/${slug}/`,d.title,d.description,slug==='company-details'&&config.sellerName&&config.sellerInn&&config.sellerAddress?'На сайте':'Готовится'])];
 return shell({title:'Документы и условия покупки | MOKWHEEL',description:'Политика конфиденциальности, согласие на обработку данных, условия оптовой продажи и документы магазина MOKWHEEL.',path:'/legal/',body:`<section class="container documents-page"><h1>Документы<br>и условия.</h1><p class="documents-intro">Всё, что относится к заявке и покупке, — в одном месте. Статус рядом с документом показывает, опубликован ли его текст.</p><div class="document-list">${entries.map(([href,title,description,status])=>`<a class="document-row" href="${href}"><div><h2>${title}</h2><p>${description}</p></div><span class="document-status ${status==='Готовится'?'pending':''}">${status}</span><span aria-hidden="true">→</span></a>`).join('')}</div><p class="documents-help">Нужны документы на конкретную партию? Позвоните <a href="tel:${config.phoneHref}">${config.phone}</a>.</p></section>`});
}
export function documentPage(slug){
 const d=pendingDocuments[slug],hasDetails=slug==='company-details'&&config.sellerName&&config.sellerInn&&config.sellerAddress;
 return shell({title:`${d.title} | MOKWHEEL`,description:d.description,path:`/legal/${slug}/`,noindex:true,body:`<article class="container document-page"><a href="/legal/">← Все документы</a><h1>${d.title}</h1>${hasDetails?`<dl class="company-details"><dt>Продавец</dt><dd>${escape(config.sellerName)}</dd><dt>ИНН</dt><dd>${escape(config.sellerInn)}</dd><dt>Адрес</dt><dd>${escape(config.sellerAddress)}</dd></dl>`:`<p class="document-status pending">Готовится к публикации</p><p>${d.description}</p><p>На этой странице пока нет опубликованного текста документа.</p>`}<a class="btn dark" href="tel:${config.phoneHref}" data-goal="phone_click">Запросить у менеджера</a></article>`});
}
