import { config, saleActive } from './config.mjs';
import { articles, articlePath } from './articles.mjs';
import { readFileSync } from 'node:fs';
export const products = JSON.parse(readFileSync(new URL('./catalog.json', import.meta.url)));
export const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = n => new Intl.NumberFormat('ru-RU').format(n) + ' ₽';
const url = path => config.origin.replace(/\/$/, '') + path;
const categoryNames = {bike:'Электровелосипеды',scooter:'Электросамокаты',moto:'Электромотоциклы'};
export const categoryPaths = {bike:'/opt/',scooter:'/elektrosamokaty/',moto:'/elektromototsikly/'};
const productPath = p => `/catalog/${p.slug}/`;
const price = p => saleActive() ? money(p.price) : 'Цена по запросу';
const publicProducts = () => products.map(p => ({slug:p.slug,name:p.name,price:saleActive()?p.price:null,variants:p.variants.filter(v=>v.stock>0).map(({sku,color})=>({sku,color}))}));
const json = v => JSON.stringify(v).replace(/</g,'\\u003c');
function brand(){return `<span class="brand-name">MOKWHEEL</span><span class="brand-address">ТК «Южные ворота», выход 5<br>линия Ж8, павильоны 122–128</span>`;}
function header(path) {
 const active=path==='/'?'home':path.startsWith('/blog/')?'blog':path.startsWith('/legal/')||['/privacy/','/terms/'].includes(path)?'legal':'wholesale';
 const links=[['home','/','Главная'],['wholesale','/opt/','Оптовый каталог'],['blog','/blog/','Блог'],['legal','/legal/','Документы']].map(([id,href,label])=>`<a href="${href}" ${id===active?'aria-current="page"':''}>${label}</a>`).join('');
 return `<header><div class="container header-inner"><a class="brand" href="/" aria-label="MOKWHEEL — главная">${brand()}</a><nav class="desktop-nav" aria-label="Основная навигация">${links}</nav><details class="mobile-nav"><summary aria-label="Открыть меню">Меню <span aria-hidden="true">⌄</span></summary><nav aria-label="Разделы сайта">${links}</nav></details><a class="phone" href="tel:${config.phoneHref}" data-goal="phone_click">${config.phone}</a></div></header>`;
}
function footer(hasForm){return `<footer><div class="container footer-grid"><div><a class="brand" href="/">${brand()}</a><p>Электровелосипеды для работы и города.</p></div><div><a class="footer-phone" href="tel:${config.phoneHref}" data-goal="phone_click">${config.phone}</a><a href="tel:+79258318777">${config.secondPhone}</a><a href="/#contacts">Как нас найти</a></div><div><a href="/opt/">Оптовый каталог</a><a href="/blog/">Блог для бизнеса</a><a href="/legal/">Документы и условия</a><a href="/privacy/">Конфиденциальность</a><small>© 2026 MOKWHEEL${config.sellerName?` · ${escape(config.sellerName)}`:''}</small></div></div></footer><div class="mobile-cta"><a href="tel:${config.phoneHref}" class="btn secondary" data-goal="phone_click">Позвонить</a><a href="${hasForm?'#request':'/opt/'}" class="btn dark">${hasForm?'Оставить заявку':'Оптовый каталог'}</a></div>`;}
export function shell({title,description,path,body,schema,noindex=false,image='/assets/store-front.jpg',type='website'}) {
 return `<!doctype html><html lang="ru"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(title)}</title><meta name="description" content="${escape(description)}"><meta name="robots" content="${noindex?'noindex, follow':'index, follow'}"><link rel="canonical" href="${escape(url(path))}"><meta name="theme-color" content="#f47b20"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(description)}"><meta property="og:type" content="${type}"><meta property="og:site_name" content="MOKWHEEL"><meta property="og:locale" content="ru_RU"><meta property="og:url" content="${escape(url(path))}"><meta property="og:image" content="${escape(url(image))}"><link rel="icon" type="image/svg+xml" href="/favicon.svg?v=2"><link rel="stylesheet" href="/style.css?v=10"><link rel="stylesheet" href="/storefront.css?v=3">${schema?`<script type="application/ld+json">${json(schema)}</script>`:''}<script id="site-data" type="application/json">${json({products:publicProducts(),bulkFrom:config.bulkFrom,saleActive:saleActive(),metrikaId:config.metrikaId})}</script><script src="/app.js?v=2" defer></script></head><body><a class="skip" href="#main">К содержимому</a>${header(path)}<main id="main">${body}</main>${footer(body.includes('id="request"'))}${config.metrikaId?'<aside id="cookie-choice" class="cookie-choice" hidden><p>Разрешить Яндекс Метрику? Она помогает нам понимать, какие модели вам интересны. Данные формы в Метрику не передаются.</p><button class="btn" id="analytics-accept">Разрешить</button><button class="text-button" id="analytics-decline">Без аналитики</button></aside>':''}</body></html>`;
}
function card(p){
 const discount=saleActive()&&p.retailPrice?Math.round((p.retailPrice-p.price)/p.retailPrice*100):0;
 const saving=saleActive()&&p.retailPrice?money(p.retailPrice-p.price):'';
 const variants=p.variants.filter(v=>v.stock>0);
 const swatches={'чёрный':'black','белый':'white','синий':'blue','зелёный':'green','розовый':'pink','красный':'red','оранжевый':'orange','серебристо-голубой':'silver-blue'};
 const colors=variants.map(v=>`<span class="color-dot color-dot--${swatches[v.color]||'other'}" title="${escape(v.color)}"></span>`).join('');
 const colorNames=variants.map(v=>v.color).join(', ');
 const retail=p.retailPrice?`<div class="retail-price"><span>Розница · за 1 шт.</span><s>${money(p.retailPrice)}</s></div>`:`<p class="retail-unavailable">Розничная цена не подтверждена</p>`;
 const source=p.retailPrice&&p.retailUrl?`<a class="price-source" href="${escape(p.retailUrl)}" target="_blank" rel="noopener">${escape(p.retailSource||'Источник розничной цены')} ↗</a>`:'';
 return `<article class="product-card"><a class="product-image" href="${productPath(p)}" aria-label="Открыть QRONGE ${escape(p.name)}"><img src="${p.image}" alt="QRONGE ${escape(p.name)}${p.imageNote?' — фото базовой модели серии':''}" loading="lazy" width="640" height="480"></a><div class="card-body"><h3><a href="${productPath(p)}">QRONGE ${escape(p.name)}</a></h3>${p.specs.length?`<p class="card-spec">${escape(p.specs.map(s=>s[1]).slice(0,2).join(' · '))}</p>`:''}<div class="color-line" aria-label="Доступные цвета">${colors}<span>${escape(variants.length?`${variants.length} ${variants.length===1?'цвет':'цвета'}`:'Цвет уточним')}</span></div><div class="price-list">${saleActive()?retail:''}<div class="wholesale-price"><span>Оптовая цена · за 1 шт.</span><strong>${saleActive()?money(p.price):'Цена по запросу'}</strong></div>${saleActive()&&p.retailPrice?`<p class="saving-row">Экономия ${saving} · ${discount}%</p>`:''}${saleActive()&&p.retailPrice?source:''}${saleActive()?`<p class="bulk-hint"><strong>Минимум ${config.bulkFrom} шт.</strong> · партия от ${money(p.price*config.bulkFrom)}</p>`:''}</div><button class="btn full" data-product="${p.slug}">Запросить оптовую цену</button><a class="details-link" href="${productPath(p)}">Все характеристики</a>${p.imageNote?`<p class="image-note">${escape(p.imageNote)}</p>`:''}</div></article>`;
}
function catalog(category='bike'){return `<section class="container wholesale-products" id="catalog"><div class="catalog-count"><p class="muted">${products.filter(p=>p.category===category).length} ${category==='bike'?'моделей':category==='scooter'?'модели':'модель'}</p></div><nav class="category-tabs" aria-label="Категории">${Object.entries(categoryNames).map(([id,label])=>`<a class="${id===category?'active':''}" ${id===category?'aria-current="page"':''} href="${categoryPaths[id]}#catalog">${label}<span>${products.filter(p=>p.category===id).length}</span></a>`).join('')}</nav><div class="product-grid">${products.filter(p=>p.category===category).map(card).join('')}</div><p class="catalog-note">${saleActive()?`Оптовая цена действует от ${config.bulkFrom} штук одной модели. Для заказа двух моделей — от ${config.bulkFrom} каждой. `:''}Розничная цена и экономия указаны только там, где удалось подтвердить сопоставимую комплектацию; источник открыт в карточке.</p></section>`;}
function requestForm(selected='') { return `<section class="request-section" id="request"><div class="container request-grid"><div class="request-copy"><h2>Запросить оптовое предложение</h2><p>Оставьте телефон и количество. Менеджер подтвердит наличие, комплектацию, цену и способ получения.</p><div class="request-contact"><span>Удобнее поговорить?</span><a href="tel:${config.phoneHref}" data-goal="phone_click">${config.phone}</a></div></div><form id="lead-form" class="lead-form" action="/api/leads" method="post"><div id="form-fields"><div class="field"><label for="model">Модель</label><select name="model" id="model"><option value="">Нужна помощь с выбором</option>${products.map(p=>`<option value="${p.slug}" ${p.slug===selected?'selected':''}>QRONGE ${escape(p.name)}${saleActive()?` — опт ${money(p.price)} / шт.; ${config.bulkFrom} шт. от ${money(p.price*config.bulkFrom)}`:''}</option>`).join('')}</select></div><div class="form-row"><div class="field"><label for="variant">Цвет</label><select name="variant" id="variant"><option value="">Уточнить с менеджером</option></select></div><div class="field quantity-field"><label for="quantity">Количество, шт.</label><input id="quantity" name="quantity" type="number" inputmode="numeric" min="${config.bulkFrom}" max="999" value="${config.bulkFrom}" required></div></div><p id="order-summary" class="order-summary" aria-live="polite">Поможем подобрать модель под ваш бюджет.</p><div class="field"><label for="phone">Ваш телефон</label><input name="phone" id="phone" type="tel" autocomplete="tel" inputmode="tel" placeholder="+7 999 123-45-67" maxlength="24" required aria-describedby="phone-hint"><small id="phone-hint">Позвоним по поводу вашей заявки.</small></div><div class="field"><label for="name">Как к вам обращаться <span class="optional">необязательно</span></label><input name="name" id="name" autocomplete="given-name" maxlength="80" placeholder="Ваше имя"></div><div class="honeypot" aria-hidden="true"><label>Ваш сайт<input name="website" tabindex="-1" autocomplete="off"></label></div><label class="consent"><input type="checkbox" name="consent" required><span>Даю <a href="/privacy/#consent" target="_blank" rel="noopener">согласие на обработку персональных данных</a> для ответа на заявку.</span></label><button class="btn full submit-btn" type="submit">Отправить заявку</button><p class="form-note">Никакой оплаты сейчас. Заявка не обязывает к покупке.</p></div><div id="form-status" role="status" aria-live="polite"></div><noscript><p>Для отправки формы включите JavaScript или позвоните ${config.phone}.</p></noscript></form></div></section>`;}
function pickup(){return `<section class="container section pickup-grid" id="pickup"><div><h2>Самовывоз или отправка<br>в любой город</h2><p class="pickup-address">${config.pickup}</p><p>Отправим заказ любой транспортной компанией. Услуги ТК оплачивает покупатель. Отгрузка — после 100% оплаты.</p><a class="btn secondary" href="https://yandex.ru/maps/?text=${encodeURIComponent(config.pickup)}" target="_blank" rel="noopener" data-goal="directions_click">Открыть в Яндекс Картах</a></div><ol class="steps"><li><span>01</span><div><h3>Вы выбираете модель и количество</h3><p>Оптовая цена — от 10 штук одной модели.</p></div></li><li><span>02</span><div><h3>Согласуем заказ и оплату</h3><p>Подтвердим наличие, комплектацию, способ отправки и итоговую сумму.</p></div></li><li><span>03</span><div><h3>Самовывоз или отправка</h3><p>Передаём заказ выбранной ТК после 100% оплаты. Доставку оплачивает покупатель.</p></div></li></ol></section>`;}
function bulk(){return `<section class="container" id="bulk"><div class="bulk-banner"><div><h2>Оптовые партии для курьерских парков и прокатов</h2><p>Снизили цены, чтобы освободить склад. Предложение рассчитано на службы доставки, компании со своими курьерами, прокаты и перепродавцов.</p><p>От 10 штук одной модели. Если берёте две модели — от 10 штук каждой.</p></div><a class="btn dark" href="tel:${config.phoneHref}">Обсудить партию</a></div></section>`;}
function faq(){return `<section class="container section faq"><div><h2>Условия покупки</h2></div><div>${[
 ['Как получить оптовую цену?',`Оптовая цена в карточке действует от ${config.bulkFrom} штук одной модели. Если заказываете две модели, нужно купить не менее ${config.bulkFrom} штук каждой.`],
 ['Можно заказать меньше 10 штук?',`Сейчас принимаем оптовые заказы от ${config.bulkFrom} штук одной модели. Если в заказе две модели — от ${config.bulkFrom} штук каждой.`],
 ['Как проходит оплата?', 'Заказ отправляется после 100% оплаты. Оплатить на этом сайте нельзя — согласуйте заказ и реквизиты с менеджером по телефону.'],
 ['Есть доставка или только самовывоз?',`Можно забрать заказ самостоятельно по адресу ${config.pickup} или отправить его любой транспортной компанией. Услуги ТК оплачивает покупатель; отгрузка — после 100% оплаты.`],
 ['До какого числа действуют цены?',saleActive()?'Текущие цены действуют по 31 октября 2026 года включительно (до 1 ноября, по московскому времени). После акции цену подтвердит менеджер.':'Текущее предложение завершено. Позвоните, чтобы узнать действующую цену.'],
 ['Как узнать точную комплектацию и условия гарантии?','Сообщите выбранную модель. До покупки менеджер подтвердит комплектацию, документы, условия гарантии и обслуживания именно для неё.']
 ].map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</div></section>`;}
export function wholesalePage(category='bike',path='/opt/') {
 const items=products.filter(p=>p.category===category),h=categoryNames[category];
 const heading=category==='bike'?'Электровелосипеды оптом':`${h} оптом`;
 return shell({title:`${heading} для бизнеса — от ${config.bulkFrom} шт. | MOKWHEEL`,description:`${h} QRONGE для курьеров, служб доставки и прокатов. Цена за единицу и стоимость партии от ${config.bulkFrom} штук одной модели. Самовывоз или отправка ТК.`,path,body:`<section class="container catalog-intro"><h1>${heading}</h1><p>${saleActive()?'Осенняя распродажа QRONGE — освобождаем склад до 1 ноября. ':''}От ${config.bulkFrom} штук одной модели. Цена за единицу и сумма партии — в каждой карточке.</p></section>${catalog(category)}${bulk()}${pickup()}${requestForm()}${faq()}`,schema:{'@context':'https://schema.org','@type':'CollectionPage',name:heading,url:url(path),mainEntity:{'@type':'ItemList',itemListElement:items.map((p,i)=>({'@type':'ListItem',position:i+1,url:url(productPath(p)),name:`QRONGE ${p.name}`}))}}});
}
export function productPage(p){
 const schema={'@context':'https://schema.org','@type':'Product',name:`QRONGE ${p.name}`,image:url(p.image),description:p.description,brand:{'@type':'Brand',name:'QRONGE'},sku:p.slug,...(saleActive()?{offers:{'@type':'Offer',url:url(productPath(p)),price:p.price,priceCurrency:'RUB',priceValidUntil:'2026-10-31',seller:{'@type':'Organization',name:config.store}}}:{})};
 const discount=saleActive()&&p.retailPrice?Math.round((p.retailPrice-p.price)/p.retailPrice*100):0;
 const saving=saleActive()&&p.retailPrice?money(p.retailPrice-p.price):'';
 return shell({title:`QRONGE ${p.name} — ${saleActive()?money(p.price)+' / шт., от 10 шт.':'узнать цену'} | MOKWHEEL`,description:`${p.description} ${saleActive()?`Оптовая цена ${money(p.price)} за единицу; минимальная партия ${config.bulkFrom} шт. — от ${money(p.price*config.bulkFrom)}. `:''}Самовывоз или отправка ТК после 100% оплаты.`,path:productPath(p),schema,body:`<div class="container"><nav class="breadcrumbs" aria-label="Хлебные крошки"><a href="/">Главная</a><span>/</span><a href="${categoryPaths[p.category]}">${categoryNames[p.category]}</a><span>/</span><span>${escape(p.name)}</span></nav><section class="product-detail"><div class="detail-photo"><img src="${p.image}" alt="QRONGE ${escape(p.name)}" width="800" height="600" fetchpriority="high">${p.imageNote?`<p>${escape(p.imageNote)}</p>`:''}</div><div class="detail-copy"><h1>QRONGE ${escape(p.name)}</h1><div class="price-list detail-prices">${saleActive()?p.retailPrice?`<div class="retail-price"><span>Розница · за 1 шт.</span><s>${money(p.retailPrice)}</s></div>`:`<p class="retail-unavailable">Розничная цена этой комплектации не подтверждена</p>`:''}<div class="wholesale-price"><span>Оптовая цена · за 1 шт.</span><strong>${saleActive()?money(p.price):'Цена по запросу'}</strong></div>${saleActive()&&p.retailPrice?`<p class="saving-row">Экономия ${saving} · ${discount}% ниже розницы</p><a class="price-source" href="${escape(p.retailUrl)}" target="_blank" rel="noopener">Источник розничной цены: ${escape(p.retailSource)} ↗</a>`:''}${saleActive()?`<p class="bulk-hint"><strong>Минимальный заказ: ${config.bulkFrom} шт.</strong> · партия от ${money(p.price*config.bulkFrom)}. При заказе двух моделей — от ${config.bulkFrom} шт. каждой.</p><p class="bulk-hint">Осенняя распродажа — до 1 ноября.</p>`:''}</div><p class="detail-description">${escape(p.description)}</p><dl>${p.specs.map(([k,v])=>`<div><dt>${escape(k)}</dt><dd>${escape(v)}</dd></div>`).join('')}<div><dt>Цвета</dt><dd>${p.variants.map(v=>escape(v.color)).join(', ')}</dd></div></dl><a class="btn" href="#request">Запросить оптовое предложение</a><p class="muted">Самовывоз или отправка любой транспортной компанией после 100% оплаты. Доставку оплачивает покупатель.</p></div></section></div>${requestForm(p.slug)}${pickup()}`});
}
export function infoPage(kind){
 const privacy=kind==='privacy', title=privacy?'Обработка персональных данных':'Условия предложения';
 const operator=config.sellerName?`${escape(config.sellerName)}, ИНН ${escape(config.sellerInn)}, адрес: ${escape(config.sellerAddress)}.`:'Реквизиты продавца будут заполнены перед открытием сайта для покупателей.';
 const body=privacy?`<p>Оператор: ${operator}</p><h2>Какие данные обрабатываются</h2><p>Номер телефона, имя (если указано), выбранная модель, цвет, количество, время и номер заявки, источник перехода и рекламные метки. Они нужны, чтобы ответить на запрос, уточнить покупку и оценить результат рекламы.</p><h2>Как используются и хранятся данные</h2><p>Заявки доступны уполномоченным сотрудникам магазина в закрытом разделе. Передача происходит по HTTPS. Срок хранения заявки — до 90 дней, после чего она автоматически удаляется, если не перенесена в отдельную систему для оформления покупки. Резервные копии могут храниться ещё до 7 дней. Сам сайт не принимает платежи.</p><h2>Аналитика</h2><p>Яндекс Метрика загружается только после вашего разрешения. Имя и телефон не передаются в цели Метрики. Выбор хранится в браузере; его можно сбросить, очистив данные сайта. Рекламные метки текущего перехода могут быть приложены к вашей заявке.</p><h2 id="consent">Согласие на обработку данных</h2><p>Отмечая поле согласия и отправляя форму, вы разрешаете оператору собирать, записывать, хранить, использовать и удалять указанные вами персональные данные для обработки заявки и связи с вами. Согласие не распространяется на рекламные рассылки. Оно действует до завершения обработки заявки, но не более 90 дней, либо до отзыва.</p><h2>Как отозвать согласие</h2><p>${config.privacyEmail?`Напишите на <a href="mailto:${escape(config.privacyEmail)}">${escape(config.privacyEmail)}</a>`:`Свяжитесь с магазином по телефону ${config.phone}`} и укажите номер заявки. Вы можете запросить уточнение или удаление данных.</p>`:`<p>${operator}</p><h2>Цены и срок акции</h2><p>Оптовая цена указана за одну единицу при покупке от ${config.bulkFrom} штук одной модели. При заказе двух моделей минимальное количество для оптовой цены — ${config.bulkFrom} единиц каждой модели. Текущие цены действуют до 1 ноября 2026 года: по 31 октября включительно, по московскому времени. После завершения предложения уточняйте актуальную стоимость.</p><h2>Наличие и комплектация</h2><p>Наличие, цвет, точную комплектацию, документы, условия гарантии и итоговую стоимость подтверждает менеджер до покупки. Иллюстрации показывают модель; цвет и отдельные элементы конкретной партии могут отличаться. Для версий M3+ и M3 Pro+ использованы фото базовых моделей серии с отдельным пояснением.</p><h2>Оплата и получение</h2><p>Отправка заказа выполняется после 100% оплаты. Можно забрать его самовывозом или заказать доставку любой транспортной компанией. Услуги ТК оплачивает покупатель.</p><h2>Самовывоз</h2><p>${config.pickup}. Перед поездкой необходимо согласовать время и подтвердить наличие.</p><h2>Покупка партии</h2><p>Оптовая цена зависит от покупки не менее ${config.bulkFrom} единиц одной модели. Если в заказе две модели — от ${config.bulkFrom} единиц каждой. Принимаются только оптовые заказы от ${config.bulkFrom} штук одной модели.</p>`;
 return shell({title:`${title} | MOKWHEEL`,description:title,path:`/${kind}/`,noindex:privacy,body:`<article class="container legal section"><a href="/">На главную</a><h1>${title}</h1>${body}</article>`});
}
export function notFound(){return shell({title:'Страница не найдена | QRONGE',description:'Перейдите в каталог QRONGE',path:'/404/',noindex:true,body:'<section class="container section legal"><p class="eyebrow">404</p><h1>Такой страницы нет.</h1><p>Выберите модель в каталоге или свяжитесь с нами.</p><a class="btn" href="/opt/">В каталог</a></section>'});}
export function sitemap(){return `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['/',...Object.values(categoryPaths),...products.map(productPath),'/blog/',...articles.map(articlePath),'/legal/','/terms/'].map(path=>`<url><loc>${escape(url(path))}</loc></url>`).join('')}</urlset>`;}
